### ISSUE TITLE
sign BasicWallet transactions

### ISSUE THREAD

**Issue by dckc** [rchain-community/RSign#11]
Let's test that we can do this... purses are typically unforgeable names, right? And so far we only sign JSON-serializable stuff...

```scala
                  new result, hashOut in {
                    @"blake2b256Hash"!([nonce, amount, retCh].toByteArray(), *hashOut) |
                    for(@hash <- hashOut) {
                      @cryptoVerify!(hash, sig.hexToBytes(), pk.hexToBytes(), *result) |
```
-- https://github.com/rchain/rchain/blob/dev/casper/src/main/rholang/BasicWallet.rho

**Comment by dckc** [comment]
See also [Support listening on unforgeable names RChain-API/issues/5](https://github.com/JoshOrndorff/RChain-API/issues/5)

**Comment by JoshOrndorff** [comment]
Here is a relevant demo from Michael Birch of using basic wallet. He produced a signature from the scala console. https://www.youtube.com/watch?v=WzAdfjwgaQs#t=9m28s

**Comment by dckc** [comment]
some progress, using `previewPrivateNames()` and `makeProxy()`:

https://github.com/dckc/RChain-API/tree/payment 3ebcd11

**Comment by dckc** [comment]
BasicWallet is obsolete in favor of REVVault.
